services:
  slave:
    image: sa_slave
    build:
      context: slave
      dockerfile: Dockerfile
    networks:
      - network
    environment:
      DB_HOST: "${DB_HOST}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
      DB_PORT: "${DB_PORT}"
      GITHUB_API_KEY: "${API_KEY}"

networks:
  network:
    driver: bridge
