services:
  master:
    image: sa_master
    build:
      context: master
      dockerfile: Dockerfile
    volumes:
      - './master:/app'
    networks:
      - network
    environment:
      REDIS_URL: "${REDIS_URL}"
      DB_HOST: "${DB_HOST}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
      DB_PORT: "${DB_PORT}"
      GITHUB_API_KEY: "${API_KEY_1}"
  slave1:
    image: sa_slave
    build:
      context: slave
      dockerfile: Dockerfile
    networks:
      - network
    environment:
      REDIS_URL: "${REDIS_URL}"
      DB_HOST: "${DB_HOST}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
      DB_PORT: "${DB_PORT}"
      GITHUB_API_KEY: "${API_KEY_1}"
      TORS_LIST: "tor11,tor12,tor13"
    depends_on:
      - tor11
      - tor12
      - tor13
  slave2:
    image: sa_slave
    build:
      context: slave
      dockerfile: Dockerfile
    networks:
      - network
    environment:
      REDIS_URL: "${REDIS_URL}"
      DB_HOST: "${DB_HOST}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
      DB_PORT: "${DB_PORT}"
      GITHUB_API_KEY: "${API_KEY_2}"
      TORS_LIST: "tor21,tor22,tor23"
    depends_on:
      - tor21
      - tor22
      - tor23
  # slave3:
  #   image: sa_slave
  #   build:
  #     context: slave
  #     dockerfile: Dockerfile
  #   networks:
  #     - network
  #   environment:
  #     REDIS_URL: "${REDIS_URL}"
  #     DB_HOST: "${DB_HOST}"
  #     DB_USER: "${DB_USER}"
  #     DB_PASSWORD: "${DB_PASSWORD}"
  #     DB_NAME: "${DB_NAME}"
  #     DB_PORT: "${DB_PORT}"
  #     GITHUB_API_KEY: "${API_KEY_3}"
  #     TORS_LIST: "tor31,tor32,tor33"
  #   depends_on:
  #     - tor31
  #     - tor32
  #     - tor33
  # db:
  #   image: mysql/mysql-server:8.0
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_ROOT_HOST: "%"
  #     MYSQL_DATABASE: mydb
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: root
  #   volumes:
  #     - mysql:/var/lib/mysql
  #   networks:
  #     - network
  tor11:
    build:
      context: ./docker/tor
      dockerfile: Dockerfile
    networks:
      - network

  tor12:
    build:
      context: ./docker/tor
      dockerfile: Dockerfile
    networks:
      - network

  tor13:
    build:
      context: ./docker/tor
      dockerfile: Dockerfile
    networks:
      - network
  tor21:
    build:
      context: ./docker/tor
      dockerfile: Dockerfile
    networks:
      - network
  tor22:
    build:
      context: ./docker/tor
      dockerfile: Dockerfile
    networks:
      - network
  tor23:
    build:
      context: ./docker/tor
      dockerfile: Dockerfile
    networks:
      - network
  # redis:
  #   image: redis:alpine
  #   networks:
  #     - network

  tor31:
    build:
      context: ./docker/tor
      dockerfile: Dockerfile
    networks:
      - network
  tor32:
    build:
      context: ./docker/tor
      dockerfile: Dockerfile
    networks:
      - network
  tor33:
    build:
      context: ./docker/tor
      dockerfile: Dockerfile
    networks:
      - network

# volumes:
#   mysql:
#     driver: local

networks:
  network:
    driver: bridge