services:
  master:
    image: sa_master
    build:
      context: master
      dockerfile: Dockerfile
    volumes:
      - './master:/app'
    networks:
      - network
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: "${REDIS_URL}"
      DB_HOST: "${DB_HOST}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
      DB_PORT: "${DB_PORT}"
      GITHUB_API_KEY: "${API_KEY_1}"
      STREAM_NAME: "my_stream_1"
  slave1:
    image: sa_slave
    build:
      context: slave
      dockerfile: Dockerfile
    networks:
      - network
    volumes:
      - './slave:/app'
    environment:
      REDIS_URL: "${REDIS_URL}"
      DB_HOST: "${DB_HOST}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
      DB_PORT: "${DB_PORT}"
      GITHUB_API_KEY: "${API_KEY_1}"
      TORS_LIST: "tor11,tor12,tor13"
      STREAM_NAME: "my_stream_1"
      GROUP_NAME: "my_group_1"
    depends_on:
      - tor11
      - tor12
      - tor13
  slave2:
    image: sa_slave
    build:
      context: slave
      dockerfile: Dockerfile
    networks:
      - network
    volumes:
      - './slave:/app'
    environment:
      REDIS_URL: "${REDIS_URL}"
      DB_HOST: "${DB_HOST}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
      DB_PORT: "${DB_PORT}"
      GITHUB_API_KEY: "${API_KEY_2}"
      TORS_LIST: "tor21,tor22,tor23"
      STREAM_NAME: "my_stream_1"
      GROUP_NAME: "my_group_1"
    depends_on:
      - tor21
      - tor22
      - tor23
  
  tor11:
    build:
      context: ./docker/tor
      dockerfile: Dockerfile
    networks:
      - network

  tor12:
    build:
      context: ./docker/tor
      dockerfile: Dockerfile
    networks:
      - network

  tor13:
    build:
      context: ./docker/tor
      dockerfile: Dockerfile
    networks:
      - network
  tor21:
    build:
      context: ./docker/tor
      dockerfile: Dockerfile
    networks:
      - network
  tor22:
    build:
      context: ./docker/tor
      dockerfile: Dockerfile
    networks:
      - network
  tor23:
    build:
      context: ./docker/tor
      dockerfile: Dockerfile
    networks:
      - network

networks:
  network:
    driver: bridge